let d = {
  data: [
    {
      filter_tp: false,
      updatetime: 1737144733,
      id: 2049,
      disablelog: 1,
      tagcache: "",
      address: 2049,
      datahex: "00",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "Entrada_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737144731,
      id: 2050,
      disablelog: 1,
      tagcache: "",
      address: 2050,
      datahex: "00",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "Intermedio_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143262,
      id: 2051,
      disablelog: 1,
      tagcache: "",
      address: 2051,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Fondo_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143264,
      id: 2052,
      disablelog: 1,
      tagcache: "",
      address: 2052,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Nevera Gaseosa agua_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143269,
      id: 2053,
      disablelog: 1,
      tagcache: "",
      address: 2053,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Aviso_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143272,
      id: 2054,
      disablelog: 1,
      tagcache: "",
      address: 2054,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Reflectores_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737144733,
      id: 2305,
      disablelog: 1,
      tagcache: "",
      address: 2305,
      datahex: "00",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "Entrada_RS_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737144731,
      id: 2306,
      disablelog: 1,
      tagcache: "",
      address: 2306,
      datahex: "00",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "Intermedio_RS_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143262,
      id: 2307,
      disablelog: 1,
      tagcache: "",
      address: 2307,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Fondo_RS_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143264,
      id: 2308,
      disablelog: 1,
      tagcache: "",
      address: 2308,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Nevera Gaseosa agua_RS_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143269,
      id: 2309,
      disablelog: 1,
      tagcache: "",
      address: 2309,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Aviso_RS_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737143272,
      id: 2310,
      disablelog: 1,
      tagcache: "",
      address: 2310,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Reflectores_RS_ON/OFF",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 2561,
      disablelog: 1,
      tagcache: "",
      address: 2561,
      datahex: "",
      datatype: 1003,
      secure: false,
      datadec: false,
      comment: "",
      name: "Entrada_RS_BLOQUEO",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 2562,
      disablelog: 1,
      tagcache: "",
      address: 2562,
      datahex: "",
      datatype: 1003,
      secure: false,
      datadec: false,
      comment: "",
      name: "Intermedio_RS_BLOQUEO",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 2563,
      disablelog: 1,
      tagcache: "",
      address: 2563,
      datahex: "",
      datatype: 1003,
      secure: false,
      datadec: false,
      comment: "",
      name: "Fondo_RS_BLOQUEO",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 2564,
      disablelog: 1,
      tagcache: "",
      address: 2564,
      datahex: "",
      datatype: 1003,
      secure: false,
      datadec: false,
      comment: "",
      name: "Nevera Gaseosa agua_RS_BLOQUEO",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 2565,
      disablelog: 1,
      tagcache: "",
      address: 2565,
      datahex: "",
      datatype: 1003,
      secure: false,
      datadec: false,
      comment: "",
      name: "Aviso_RS_BLOQUEO",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 2566,
      disablelog: 1,
      tagcache: "",
      address: 2566,
      datahex: "",
      datatype: 1003,
      secure: false,
      datadec: false,
      comment: "",
      name: "Reflectores_RS_BLOQUEO",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737202296,
      id: 2817,
      disablelog: 1,
      tagcache: "",
      address: 2817,
      datahex: "001B",
      datatype: 7,
      secure: false,
      datadec: 27,
      comment: "",
      name: "Entrada_TI_FUN",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737202296,
      id: 2818,
      disablelog: 1,
      tagcache: "",
      address: 2818,
      datahex: "0000",
      datatype: 7,
      secure: false,
      datadec: 0,
      comment: "",
      name: "Intermedio_TI_FUN",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737202296,
      id: 2819,
      disablelog: 1,
      tagcache: "",
      address: 2819,
      datahex: "0010",
      datatype: 7,
      secure: false,
      datadec: 16,
      comment: "",
      name: "Fondo_TI_FUN",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737202296,
      id: 2820,
      disablelog: 1,
      tagcache: "",
      address: 2820,
      datahex: "0010",
      datatype: 7,
      secure: false,
      datadec: 16,
      comment: "",
      name: "Nevera Gaseosa agua_TI_FUN",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737202297,
      id: 2821,
      disablelog: 1,
      tagcache: "",
      address: 2821,
      datahex: "0010",
      datatype: 7,
      secure: false,
      datadec: 16,
      comment: "",
      name: "Aviso_TI_FUN",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737202297,
      id: 2822,
      disablelog: 1,
      tagcache: "",
      address: 2822,
      datahex: "0010",
      datatype: 7,
      secure: false,
      datadec: 16,
      comment: "",
      name: "Reflectores_TI_FUN",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4097,
      disablelog: 1,
      tagcache: "",
      address: 4097,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Entrada luces",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4098,
      disablelog: 1,
      tagcache: "",
      address: 4098,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Intermedio Luces",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4099,
      disablelog: 1,
      tagcache: "",
      address: 4099,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Fondo Luces",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4100,
      disablelog: 1,
      tagcache: "",
      address: 4100,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Nevera Gaseosa agua",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4101,
      disablelog: 1,
      tagcache: "",
      address: 4101,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Aviso",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4102,
      disablelog: 1,
      tagcache: "",
      address: 4102,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Reflectores",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4103,
      disablelog: 1,
      tagcache: "",
      address: 4103,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Aire acondicionado # 1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4104,
      disablelog: 1,
      tagcache: "",
      address: 4104,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Aire acondicionado # 2 Intermedio",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4105,
      disablelog: 1,
      tagcache: "",
      address: 4105,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "Señal selector AUTO Aire acondicionado # 2 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 4353,
      disablelog: 1,
      tagcache: "",
      address: 4353,
      datahex: "",
      datatype: 9001,
      secure: false,
      datadec: 0,
      comment: "",
      name: "Temperatura del recinto",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870360,
      id: 6145,
      disablelog: 1,
      tagcache: "",
      address: 6145,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "ON AACC  #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870377,
      id: 6146,
      disablelog: 1,
      tagcache: "",
      address: 6146,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "OFF AACC  #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121546,
      id: 6149,
      disablelog: 1,
      tagcache: "",
      address: 6149,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "16°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121553,
      id: 6150,
      disablelog: 1,
      tagcache: "",
      address: 6150,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "17°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121570,
      id: 6151,
      disablelog: 1,
      tagcache: "",
      address: 6151,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "18°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121576,
      id: 6152,
      disablelog: 1,
      tagcache: "",
      address: 6152,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "19°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121582,
      id: 6153,
      disablelog: 1,
      tagcache: "",
      address: 6153,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "20°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121587,
      id: 6154,
      disablelog: 1,
      tagcache: "",
      address: 6154,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "21°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121594,
      id: 6155,
      disablelog: 1,
      tagcache: "",
      address: 6155,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "22°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121705,
      id: 6156,
      disablelog: 1,
      tagcache: "",
      address: 6156,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "23°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121712,
      id: 6157,
      disablelog: 1,
      tagcache: "",
      address: 6157,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "24°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121723,
      id: 6158,
      disablelog: 1,
      tagcache: "",
      address: 6158,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "25°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121729,
      id: 6159,
      disablelog: 1,
      tagcache: "",
      address: 6159,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "26°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121776,
      id: 6160,
      disablelog: 1,
      tagcache: "",
      address: 6160,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "27°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121740,
      id: 6161,
      disablelog: 1,
      tagcache: "",
      address: 6161,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "28°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121745,
      id: 6162,
      disablelog: 1,
      tagcache: "",
      address: 6162,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "29°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121751,
      id: 6163,
      disablelog: 1,
      tagcache: "",
      address: 6163,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "30°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121757,
      id: 6164,
      disablelog: 1,
      tagcache: "",
      address: 6164,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "31°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121762,
      id: 6165,
      disablelog: 1,
      tagcache: "",
      address: 6165,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "32°C AACC #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870358,
      id: 6166,
      disablelog: 1,
      tagcache: "",
      address: 6166,
      datahex: "01",
      datatype: 1006,
      secure: false,
      datadec: true,
      comment: "",
      name: "Contactor Potencia #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737132955,
      id: 6167,
      disablelog: 1,
      tagcache: "",
      address: 6167,
      datahex: "00",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "RS_Contactor Potencia #1 Entrada",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870377,
      id: 6168,
      disablelog: 1,
      tagcache: "",
      address: 6168,
      datahex: "00",
      datatype: 1002,
      secure: false,
      datadec: false,
      comment: "",
      name: "ON/OFF AACC  #1 Entrada General",
      filter_ip: false,
    },
    {
      filter_tp: false,
      visparams:
        '{"max":"32","scale":"100","control":"spinner","min":"16","popover_bgcolor":"","popover_bgtransparency":"0","decimals":"0","step":"1"}',
      updatetime: 1737121776,
      id: 6169,
      disablelog: 1,
      tagcache: "",
      address: 6169,
      datahex: "0D46",
      datatype: 9001,
      secure: false,
      datadec: 27,
      comment: "",
      name: "TEMPERATURA AACC  #1 Entrada  General",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6401,
      disablelog: 1,
      tagcache: "",
      address: 6401,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "ON AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6402,
      disablelog: 1,
      tagcache: "",
      address: 6402,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "OFF AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121938,
      id: 6405,
      disablelog: 1,
      tagcache: "",
      address: 6405,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "16°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121944,
      id: 6406,
      disablelog: 1,
      tagcache: "",
      address: 6406,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "17°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121949,
      id: 6407,
      disablelog: 1,
      tagcache: "",
      address: 6407,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "18°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737121954,
      id: 6408,
      disablelog: 1,
      tagcache: "",
      address: 6408,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "19°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122104,
      id: 6409,
      disablelog: 1,
      tagcache: "",
      address: 6409,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "20°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122110,
      id: 6410,
      disablelog: 1,
      tagcache: "",
      address: 6410,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "21°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122115,
      id: 6411,
      disablelog: 1,
      tagcache: "",
      address: 6411,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "22°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122119,
      id: 6412,
      disablelog: 1,
      tagcache: "",
      address: 6412,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "23°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122126,
      id: 6413,
      disablelog: 1,
      tagcache: "",
      address: 6413,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "24°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122130,
      id: 6414,
      disablelog: 1,
      tagcache: "",
      address: 6414,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "25°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122139,
      id: 6415,
      disablelog: 1,
      tagcache: "",
      address: 6415,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "26°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122145,
      id: 6416,
      disablelog: 1,
      tagcache: "",
      address: 6416,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "27°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122153,
      id: 6417,
      disablelog: 1,
      tagcache: "",
      address: 6417,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "28°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122158,
      id: 6418,
      disablelog: 1,
      tagcache: "",
      address: 6418,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "29°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122165,
      id: 6419,
      disablelog: 1,
      tagcache: "",
      address: 6419,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "30°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122173,
      id: 6420,
      disablelog: 1,
      tagcache: "",
      address: 6420,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "31°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122184,
      id: 6421,
      disablelog: 1,
      tagcache: "",
      address: 6421,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "32°C AACC #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6422,
      disablelog: 1,
      tagcache: "",
      address: 6422,
      datahex: "",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "Contactor Potencia #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737144930,
      id: 6423,
      disablelog: 1,
      tagcache: "",
      address: 6423,
      datahex: "00",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "RS_Contactor Potencia #2 Mitad",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6424,
      disablelog: 1,
      tagcache: "",
      address: 6424,
      datahex: "",
      datatype: 1002,
      secure: false,
      datadec: false,
      comment: "",
      name: "ON/OFF AACC  #2 Mitad General",
      filter_ip: false,
    },
    {
      filter_tp: false,
      visparams:
        '{"max":"32","scale":"100","control":"spinner","min":"16","popover_bgcolor":"","popover_bgtransparency":"0","decimals":"0","step":"1"}',
      updatetime: 1737122184,
      id: 6425,
      disablelog: 1,
      tagcache: "",
      address: 6425,
      datahex: "0E40",
      datatype: 9001,
      secure: false,
      datadec: 32,
      comment: "",
      name: "TEMPERATURA AACC  #2 Mitad General",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6657,
      disablelog: 1,
      tagcache: "",
      address: 6657,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "ON AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6658,
      disablelog: 1,
      tagcache: "",
      address: 6658,
      datahex: "",
      datatype: 1001,
      secure: false,
      datadec: false,
      comment: "",
      name: "OFF AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122304,
      id: 6661,
      disablelog: 1,
      tagcache: "",
      address: 6661,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "16°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122315,
      id: 6662,
      disablelog: 1,
      tagcache: "",
      address: 6662,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "17°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122321,
      id: 6663,
      disablelog: 1,
      tagcache: "",
      address: 6663,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "18°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122419,
      id: 6664,
      disablelog: 1,
      tagcache: "",
      address: 6664,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "19°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737123261,
      id: 6665,
      disablelog: 1,
      tagcache: "",
      address: 6665,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "20°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122336,
      id: 6666,
      disablelog: 1,
      tagcache: "",
      address: 6666,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "21°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122342,
      id: 6667,
      disablelog: 1,
      tagcache: "",
      address: 6667,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "22°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122347,
      id: 6668,
      disablelog: 1,
      tagcache: "",
      address: 6668,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "23°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122353,
      id: 6669,
      disablelog: 1,
      tagcache: "",
      address: 6669,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "24°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122359,
      id: 6670,
      disablelog: 1,
      tagcache: "",
      address: 6670,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "25°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122366,
      id: 6671,
      disablelog: 1,
      tagcache: "",
      address: 6671,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "26°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122372,
      id: 6672,
      disablelog: 1,
      tagcache: "",
      address: 6672,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "27°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122377,
      id: 6673,
      disablelog: 1,
      tagcache: "",
      address: 6673,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "28°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122382,
      id: 6674,
      disablelog: 1,
      tagcache: "",
      address: 6674,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "29°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122388,
      id: 6675,
      disablelog: 1,
      tagcache: "",
      address: 6675,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "30°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122394,
      id: 6676,
      disablelog: 1,
      tagcache: "",
      address: 6676,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "31°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1737122400,
      id: 6677,
      disablelog: 1,
      tagcache: "",
      address: 6677,
      datahex: "01",
      datatype: 1001,
      secure: false,
      datadec: true,
      comment: "",
      name: "32°C AACC #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6678,
      disablelog: 1,
      tagcache: "",
      address: 6678,
      datahex: "",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "Contactor Potencia #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6679,
      disablelog: 1,
      tagcache: "",
      address: 6679,
      datahex: "",
      datatype: 1006,
      secure: false,
      datadec: false,
      comment: "",
      name: "RS_Contactor Potencia #3 Fondo",
      filter_ip: false,
    },
    {
      filter_tp: false,
      updatetime: 1736870035,
      id: 6680,
      disablelog: 1,
      tagcache: "",
      address: 6680,
      datahex: "",
      datatype: 1002,
      secure: false,
      datadec: false,
      comment: "",
      name: "ON/OFF AACC  #3 Fondo General",
      filter_ip: false,
    },
    {
      filter_tp: false,
      visparams:
        '{"max":"32","scale":"100","control":"spinner","min":"16","popover_bgcolor":"","popover_bgtransparency":"0","decimals":"0","step":"1"}',
      updatetime: 1737123261,
      id: 6681,
      disablelog: 1,
      tagcache: "",
      address: 6681,
      datahex: "07D0",
      datatype: 9001,
      secure: false,
      datadec: 20,
      comment: "",
      name: "TEMPERATURA AACC  #3 Fondo General",
      filter_ip: false,
    },
    {
      id: 67585,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "1E56",
      units: " V",
      comment: "",
      visparams: "",
      updatetime: 1737208276,
      datatype: 9,
      readoninit: "",
      datadec: 129.76,
      name: "Medidor de energia - Voltaje Fase A #1",
      export: "",
      pollinterval: "",
      address: 67585,
      covincr: "",
      enums: "",
    },
    {
      id: 67586,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "1645",
      units: " V",
      comment: "",
      visparams: "",
      updatetime: 1737207821,
      datatype: 9,
      readoninit: "",
      datadec: 64.2,
      name: "Medidor de energia - Voltaje Fase B #1",
      export: "",
      pollinterval: "",
      address: 67586,
      covincr: "",
      enums: "",
    },
    {
      id: 67587,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "1640",
      units: " V",
      comment: "",
      visparams: "",
      updatetime: 1737207866,
      datatype: 9,
      readoninit: "",
      datadec: 64,
      name: "Medidor de energia - Voltaje Fase C #1",
      export: "",
      pollinterval: "",
      address: 67587,
      covincr: "",
      enums: "",
    },
    {
      id: 67588,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "15DA",
      units: " Hz",
      comment: "",
      visparams: "",
      updatetime: 1737132867,
      datatype: 9,
      readoninit: "",
      datadec: 59.92,
      name: "Medidor de energia - Frecuencia",
      export: "",
      pollinterval: "",
      address: 67588,
      covincr: "",
      enums: "",
    },
    {
      id: 67589,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978848,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67589,
      covincr: "",
      enums: "",
    },
    {
      id: 67590,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978853,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67590,
      covincr: "",
      enums: "",
    },
    {
      id: 67591,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978859,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67591,
      covincr: "",
      enums: "",
    },
    {
      id: 67592,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978871,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67592,
      covincr: "",
      enums: "",
    },
    {
      id: 67593,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0000",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978865,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67593,
      covincr: "",
      enums: "",
    },
    {
      id: 67594,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978876,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67594,
      covincr: "",
      enums: "",
    },
    {
      id: 67595,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978888,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67595,
      covincr: "",
      enums: "",
    },
    {
      id: 67596,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978895,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67596,
      covincr: "",
      enums: "",
    },
    {
      id: 67597,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978901,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67597,
      covincr: "",
      enums: "",
    },
    {
      id: 67598,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978913,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67598,
      covincr: "",
      enums: "",
    },
    {
      id: 67599,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1736978919,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Corriente C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67599,
      covincr: "",
      enums: "",
    },
    {
      id: 67600,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978924,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67600,
      covincr: "",
      enums: "",
    },
    {
      id: 67601,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978932,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67601,
      covincr: "",
      enums: "",
    },
    {
      id: 67602,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978936,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia C, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67602,
      covincr: "",
      enums: "",
    },
    {
      id: 67603,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978941,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67603,
      covincr: "",
      enums: "",
    },
    {
      id: 67604,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978956,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67604,
      covincr: "",
      enums: "",
    },
    {
      id: 67605,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978961,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67605,
      covincr: "",
      enums: "",
    },
    {
      id: 67606,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978966,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67606,
      covincr: "",
      enums: "",
    },
    {
      id: 67607,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978971,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67607,
      covincr: "",
      enums: "",
    },
    {
      id: 67608,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978978,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67608,
      covincr: "",
      enums: "",
    },
    {
      id: 67609,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978982,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67609,
      covincr: "",
      enums: "",
    },
    {
      id: 67610,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978988,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67610,
      covincr: "",
      enums: "",
    },
    {
      id: 67611,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978993,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67611,
      covincr: "",
      enums: "",
    },
    {
      id: 67612,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736978998,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Total, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67612,
      covincr: "",
      enums: "",
    },
    {
      id: 67613,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736979003,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Total, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67613,
      covincr: "",
      enums: "",
    },
    {
      id: 67614,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736979066,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Total, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67614,
      covincr: "",
      enums: "",
    },
    {
      id: 67615,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " W",
      comment: "",
      visparams: "",
      updatetime: 1736979070,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Total, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67615,
      covincr: "",
      enums: "",
    },
    {
      id: 67616,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979077,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67616,
      covincr: "",
      enums: "",
    },
    {
      id: 67617,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979084,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67617,
      covincr: "",
      enums: "",
    },
    {
      id: 67618,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979089,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva C, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67618,
      covincr: "",
      enums: "",
    },
    {
      id: 67619,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979095,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67619,
      covincr: "",
      enums: "",
    },
    {
      id: 67620,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979100,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67620,
      covincr: "",
      enums: "",
    },
    {
      id: 67621,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979105,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67621,
      covincr: "",
      enums: "",
    },
    {
      id: 67622,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979110,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67622,
      covincr: "",
      enums: "",
    },
    {
      id: 67623,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979117,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67623,
      covincr: "",
      enums: "",
    },
    {
      id: 67624,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979121,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67624,
      covincr: "",
      enums: "",
    },
    {
      id: 67625,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979130,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67625,
      covincr: "",
      enums: "",
    },
    {
      id: 67626,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1737045296,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67626,
      covincr: "",
      enums: "",
    },
    {
      id: 67627,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979139,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67627,
      covincr: "",
      enums: "",
    },
    {
      id: 67628,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979143,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva Total, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67628,
      covincr: "",
      enums: "",
    },
    {
      id: 67629,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979148,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva Total, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67629,
      covincr: "",
      enums: "",
    },
    {
      id: 67630,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979153,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva Total, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67630,
      covincr: "",
      enums: "",
    },
    {
      id: 67631,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " Var",
      comment: "",
      visparams: "",
      updatetime: 1736979158,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Reactiva Total, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67631,
      covincr: "",
      enums: "",
    },
    {
      id: 67632,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979167,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67632,
      covincr: "",
      enums: "",
    },
    {
      id: 67633,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979171,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67633,
      covincr: "",
      enums: "",
    },
    {
      id: 67634,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979175,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia C, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67634,
      covincr: "",
      enums: "",
    },
    {
      id: 67635,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0000",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979179,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67635,
      covincr: "",
      enums: "",
    },
    {
      id: 67636,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979181,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67636,
      covincr: "",
      enums: "",
    },
    {
      id: 67637,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979183,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67637,
      covincr: "",
      enums: "",
    },
    {
      id: 67638,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979186,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67638,
      covincr: "",
      enums: "",
    },
    {
      id: 67639,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979189,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67639,
      covincr: "",
      enums: "",
    },
    {
      id: 67640,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979193,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67640,
      covincr: "",
      enums: "",
    },
    {
      id: 67641,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0000",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979197,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67641,
      covincr: "",
      enums: "",
    },
    {
      id: 67642,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979198,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67642,
      covincr: "",
      enums: "",
    },
    {
      id: 67643,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979201,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67643,
      covincr: "",
      enums: "",
    },
    {
      id: 67644,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0000",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979207,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia Total, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67644,
      covincr: "",
      enums: "",
    },
    {
      id: 67645,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979208,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia Total, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67645,
      covincr: "",
      enums: "",
    },
    {
      id: 67646,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979211,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia Total, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67646,
      covincr: "",
      enums: "",
    },
    {
      id: 67647,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0000",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736979216,
      datatype: 9,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Factor de Potencia Total, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67647,
      covincr: "",
      enums: "",
    },
    {
      id: 67648,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1736979242,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67648,
      covincr: "",
      enums: "",
    },
    {
      id: 67649,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1736979247,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67649,
      covincr: "",
      enums: "",
    },
    {
      id: 67650,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1736979259,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente C, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67650,
      covincr: "",
      enums: "",
    },
    {
      id: 67651,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1736979264,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67651,
      covincr: "",
      enums: "",
    },
    {
      id: 67652,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1736979270,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67652,
      covincr: "",
      enums: "",
    },
    {
      id: 67653,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045316,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67653,
      covincr: "",
      enums: "",
    },
    {
      id: 67654,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045321,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67654,
      covincr: "",
      enums: "",
    },
    {
      id: 67655,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045327,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67655,
      covincr: "",
      enums: "",
    },
    {
      id: 67656,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045333,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67656,
      covincr: "",
      enums: "",
    },
    {
      id: 67657,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045341,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67657,
      covincr: "",
      enums: "",
    },
    {
      id: 67658,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045348,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67658,
      covincr: "",
      enums: "",
    },
    {
      id: 67659,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045352,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67659,
      covincr: "",
      enums: "",
    },
    {
      id: 67660,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045358,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente Total, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67660,
      covincr: "",
      enums: "",
    },
    {
      id: 67661,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045363,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente Total, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67661,
      covincr: "",
      enums: "",
    },
    {
      id: 67662,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045367,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente Total, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67662,
      covincr: "",
      enums: "",
    },
    {
      id: 67663,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " VA",
      comment: "",
      visparams: "",
      updatetime: 1737045372,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Potencia Aparente Total, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67663,
      covincr: "",
      enums: "",
    },
    {
      id: 67664,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045378,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67664,
      covincr: "",
      enums: "",
    },
    {
      id: 67665,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045384,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67665,
      covincr: "",
      enums: "",
    },
    {
      id: 67666,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045390,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase C, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67666,
      covincr: "",
      enums: "",
    },
    {
      id: 67667,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045395,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67667,
      covincr: "",
      enums: "",
    },
    {
      id: 67668,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045400,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67668,
      covincr: "",
      enums: "",
    },
    {
      id: 67669,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045406,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67669,
      covincr: "",
      enums: "",
    },
    {
      id: 67670,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045412,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67670,
      covincr: "",
      enums: "",
    },
    {
      id: 67671,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045418,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67671,
      covincr: "",
      enums: "",
    },
    {
      id: 67672,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045427,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67672,
      covincr: "",
      enums: "",
    },
    {
      id: 67673,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045423,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67673,
      covincr: "",
      enums: "",
    },
    {
      id: 67674,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045434,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67674,
      covincr: "",
      enums: "",
    },
    {
      id: 67675,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045438,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Fase C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67675,
      covincr: "",
      enums: "",
    },
    {
      id: 67676,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045444,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Total, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67676,
      covincr: "",
      enums: "",
    },
    {
      id: 67677,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045450,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Total, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67677,
      covincr: "",
      enums: "",
    },
    {
      id: 67678,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045459,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Total, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67678,
      covincr: "",
      enums: "",
    },
    {
      id: 67679,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kWh",
      comment: "",
      visparams: "",
      updatetime: 1737045465,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Total, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67679,
      covincr: "",
      enums: "",
    },
    {
      id: 67680,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045471,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase A, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67680,
      covincr: "",
      enums: "",
    },
    {
      id: 67681,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045476,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase B, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67681,
      covincr: "",
      enums: "",
    },
    {
      id: 67682,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045481,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase C, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67682,
      covincr: "",
      enums: "",
    },
    {
      id: 67683,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045487,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase A, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67683,
      covincr: "",
      enums: "",
    },
    {
      id: 67684,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045494,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase B, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67684,
      covincr: "",
      enums: "",
    },
    {
      id: 67685,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045499,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase C, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67685,
      covincr: "",
      enums: "",
    },
    {
      id: 67686,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045506,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase A, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67686,
      covincr: "",
      enums: "",
    },
    {
      id: 67687,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045511,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase B, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67687,
      covincr: "",
      enums: "",
    },
    {
      id: 67688,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045516,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase C, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67688,
      covincr: "",
      enums: "",
    },
    {
      id: 67689,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045522,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase A, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67689,
      covincr: "",
      enums: "",
    },
    {
      id: 67690,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045528,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase B, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67690,
      covincr: "",
      enums: "",
    },
    {
      id: 67691,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045534,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Fase C, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67691,
      covincr: "",
      enums: "",
    },
    {
      id: 67692,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045539,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Total, Circuito 1",
      export: "",
      pollinterval: "",
      address: 67692,
      covincr: "",
      enums: "",
    },
    {
      id: 67693,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045549,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Total, Circuito 2",
      export: "",
      pollinterval: "",
      address: 67693,
      covincr: "",
      enums: "",
    },
    {
      id: 67694,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045557,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Total, Circuito 3",
      export: "",
      pollinterval: "",
      address: 67694,
      covincr: "",
      enums: "",
    },
    {
      id: 67695,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "00000000",
      units: " kvarh",
      comment: "",
      visparams: "",
      updatetime: 1737045562,
      datatype: 14,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Energia Reactiva hora Total, Circuito 4",
      export: "",
      pollinterval: "",
      address: 67695,
      covincr: "",
      enums: "",
    },
    {
      id: 67696,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0064",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736980416,
      datatype: 9,
      readoninit: "",
      datadec: 1,
      name: "Medidor de energia - Direccion de Comunicacion",
      export: "",
      pollinterval: "",
      address: 67696,
      covincr: "",
      enums: "",
    },
    {
      id: 67697,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "0064",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736980416,
      datatype: 9,
      readoninit: "",
      datadec: 1,
      name: "Medidor de energia - Tasa de Baudio",
      export: "",
      pollinterval: "",
      address: 67697,
      covincr: "",
      enums: "",
    },
    {
      id: 67698,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "1CE2",
      units: " A",
      comment: "",
      visparams: "",
      updatetime: 1737045568,
      datatype: 9,
      readoninit: "",
      datadec: 100,
      name: "Medidor de energia - CT Primaria",
      export: "",
      pollinterval: "",
      address: 67698,
      covincr: "",
      enums: "",
    },
    {
      id: 67699,
      disablelog: 1,
      tagcache: "",
      secure: false,
      datahex: "",
      units: "",
      comment: "",
      visparams: "",
      updatetime: 1736980421,
      datatype: 7,
      readoninit: "",
      datadec: 0,
      name: "Medidor de energia - Reset Energia",
      export: "",
      pollinterval: "",
      address: 67699,
      covincr: "",
      enums: "",
    },
    {
      secure: false,
      updatetime: 1737045273,
      id: 67700,
      datadec: 0,
      disablelog: 1,
      tagcache: "",
      datatype: 9,
      readoninit: 0,
      datahex: "",
      units: " A",
      pollinterval: "",
      export: 0,
      comment: "",
      name: "Medidor de energia - Corriente C, Circuito 1",
      address: 67700,
    },
  ],
  updatetime: null,
  tags: [],
};
