const directionsNames = {
  "1/1/1": "Luz Entrada",
  "1/1/2": "Luz Intermedio",
  "1/1/3": "Luz Fondo",
  "1/1/4": "Nevera Gaseosa",
  "1/1/5": "Luz Aviso",
  "1/1/6": "Reflectores",
  "1/3/1": "Tiempo Funcionamiento Luz Entrada",
  "1/3/2": "Tiempo Funcionamiento Luz Intermedio",
  "1/3/3": "Tiempo Funcionamiento Luz Fondo",
  "1/3/4": "Tiempo Funcionamiento Nevera Gaseosa",
  "1/3/5": "Tiempo Funcionamiento Luz Aviso",
  "1/3/6": "Tiempo Funcionamiento Reflectores",
  "2/0/1": "Señal Selector Luz Entrada",
  "2/0/2": "Señal Selector Luz Intermedio",
  "2/0/3": "Señal Selector Luz Fondo",
  "2/0/4": "Señal Selector Nevera Gaseosa",
  "2/0/5": "Señal Selector Luz Aviso",
  "2/0/6": "Señal Selector Reflectores",
  "2/1/1": "Temperatura del Recinto",
  "3/0/24": "Aire Entrada",
  "3/0/25": "Temperatura Aire Entrada",
  "3/1/24": "Aire Mitad",
  "3/1/25": "Temperatura Aire Mitad",
  "3/2/24": "Aire Fondo",
  "3/2/25": "Temperatura Aire Fondo",
  "33/0/1": "Medidor de Energia - Voltaje",
};

